services:
    replicator:
        image: ghcr.io/xzeldon/livesync-replicator:latest
        container_name: livesync-replicator
        restart: unless-stopped
        volumes:
            - ./vault:/app/vault
        env_file:
            - .env
        environment:
            - PUID=1000
            - PGID=1000
            - LIVESYNC_INTERVAL=3600 # Every hour
